apiVersion: v2
type: application

home: https://github.com/topolvm/topolvm
name: topolvm
description: Topolvm
version: 0.1.9
appVersion: 0.1.9
sources:
  - https://github.com/topolvm/topolvm

dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: 1.7.0
    condition: cert-manager.enabled

annotations:
  artifacthub.io/images: |
    - name: topolvm-with-sidecar
      image: ghcr.io/topolvm/topolvm-with-sidecar:0.1.9
    - name: topolvm-with
      image: ghcr.io/topolvm/topolvm:0.1.9
  artifacthub.io/license: Apache-2.0
